# Copyright (c) 2024-2026 Abneesh Singh. All rights reserved.
# Proprietary and Confidential - see LICENSE.txt
"""
NeuroShell Provenance Tracker
Tags every suggestion with its source for trust and transparency.
"""

from dataclasses import dataclass
from enum import Enum


class ProvenanceSource(Enum):
    """Where a suggestion came from."""
    LLM = "LLM"           # Generated by the language model
    CACHED = "CACHED"     # From error fix cache (proven fix)
    PATTERN = "PATTERN"   # From learned user patterns
    PLUGIN = "PLUGIN"     # From a loaded plugin
    HISTORY = "HISTORY"   # From command history match
    DEPENDENCY = "DEP"    # From dependency resolver
    NLP = "NLP"           # From NLP classifier/extractor
    FALLBACK = "FALLBACK" # From graceful degradation fallback


@dataclass
class ProvenanceTag:
    """Provenance metadata attached to a suggestion."""
    source: ProvenanceSource
    confidence: float = 0.0
    detail: str = ""       # e.g., "cached fix used 12 times successfully"
    latency_ms: float = 0

    @property
    def badge(self) -> str:
        """Formatted badge for display."""
        return f"[{self.source.value}]"

    @property
    def trust_level(self) -> str:
        """Human-readable trust level."""
        if self.source == ProvenanceSource.CACHED:
            return "Proven (cached fix)"
        elif self.source == ProvenanceSource.PATTERN:
            return "Learned (from your patterns)"
        elif self.source == ProvenanceSource.HISTORY:
            return "Historical (from your history)"
        elif self.source == ProvenanceSource.LLM:
            if self.confidence >= 0.9:
                return "High confidence (AI)"
            elif self.confidence >= 0.7:
                return "Medium confidence (AI)"
            else:
                return "Low confidence (AI guess)"
        elif self.source == ProvenanceSource.DEPENDENCY:
            return "System check"
        elif self.source == ProvenanceSource.NLP:
            return "NLP classified"
        elif self.source == ProvenanceSource.FALLBACK:
            return "Fallback (degraded mode)"
        return "Unknown"


class ProvenanceTracker:
    """Tracks provenance statistics across the session."""

    def __init__(self):
        self._counts: dict[str, int] = {}
        self._total = 0

    def record(self, tag: ProvenanceTag):
        """Record a provenance event."""
        source = tag.source.value
        self._counts[source] = self._counts.get(source, 0) + 1
        self._total += 1

    def get_stats(self) -> dict:
        """Get provenance breakdown stats."""
        if self._total == 0:
            return {"total": 0, "breakdown": {}}

        breakdown = {}
        for source, count in self._counts.items():
            breakdown[source] = {
                "count": count,
                "percentage": round(count / self._total * 100, 1),
            }

        return {"total": self._total, "breakdown": breakdown}

    def get_summary(self) -> str:
        """Human-readable provenance summary."""
        stats = self.get_stats()
        if stats["total"] == 0:
            return "No suggestions yet"

        parts = []
        for source, data in stats["breakdown"].items():
            parts.append(f"{source}: {data['percentage']}%")

        return f"{stats['total']} suggestions — {', '.join(parts)}"
