# Copyright (c) 2024-2026 Abneesh Singh. All rights reserved.
# Proprietary and Confidential - see LICENSE.txt
"""
NeuroShell LLM Response Sanitizer — Production Grade
Post-LLM command validation to prevent execution of malicious,
malformed, or nonsensical commands generated by the model.
"""

import re
import platform
from typing import Optional
from dataclasses import dataclass


@dataclass
class SanitizationResult:
    """Result of sanitizing an LLM-generated command."""
    command: str
    is_safe: bool
    warnings: list[str]
    was_modified: bool = False
    original: str = ""


# Maximum allowed command length (chars)
MAX_COMMAND_LENGTH = 2000

# Patterns that should NEVER appear in LLM-generated commands
FORBIDDEN_PATTERNS = [
    # Remote code execution
    (r"curl\s+.+\|\s*(?:ba)?sh", "Remote code execution via piped curl"),
    (r"wget\s+.+\|\s*(?:ba)?sh", "Remote code execution via piped wget"),
    (r"eval\s+\"\$\(curl", "Remote eval via curl"),
    (r"eval\s+\"\$\(wget", "Remote eval via wget"),
    (r"python\s+-c\s+['\"]import\s+urllib", "Remote code fetch via Python"),

    # System destruction
    (r"rm\s+-rf\s+/\s*$", "Root filesystem deletion"),
    (r"rm\s+-rf\s+~\s*$", "Home directory deletion"),
    (r":\(\)\{\s*:\|:\s*&\s*\};:", "Fork bomb"),
    (r"dd\s+if=.+of=/dev/", "Raw disk write"),
    (r"mkfs\.", "Filesystem format"),
    (r"format\s+[a-zA-Z]:", "Windows disk format"),
    (r"del\s+/[sS]\s+/[qQ]\s+[cC]:\\\\", "Windows recursive C: drive delete"),

    # Encoded/obfuscated commands
    (r"\\x[0-9a-fA-F]{2}.*\\x[0-9a-fA-F]{2}", "Hex-encoded payload"),
    (r"base64\s+-d\s*\|\s*(?:ba)?sh", "Base64-decoded script execution"),
    (r"echo\s+[A-Za-z0-9+/=]{50,}\s*\|\s*base64", "Base64-encoded command blob"),

    # Credential theft
    (r"cat\s+.*/etc/shadow", "Shadow file access"),
    (r"cat\s+.*/etc/passwd", "Password file access"),
    (r"type\s+.*\.ssh/", "SSH key access"),
    (r"reg\s+query\s+.*password", "Registry password query"),
]

# Compiled forbidden patterns
_FORBIDDEN_COMPILED = [(re.compile(p, re.IGNORECASE), desc) for p, desc in FORBIDDEN_PATTERNS]

# Shell metacharacters that LLMs sometimes hallucinate incorrectly
SUSPICIOUS_SEQUENCES = [
    (r";\s*rm\s", "Semicolon followed by rm — possible injection"),
    (r"&&\s*rm\s", "Chain followed by rm — possible injection"),
    (r"\|\s*mail\s", "Piping to mail — data exfiltration risk"),
    (r"\|\s*nc\s", "Piping to netcat — data exfiltration risk"),
    (r"\|\s*curl\s+-X\s*POST", "Piping to curl POST — data exfiltration risk"),
    (r">\s*/dev/sd[a-z]", "Redirect to raw disk device"),
    (r"2>&1\s*\|\s*tee\s+/etc/", "Overwriting system config via tee"),
]

_SUSPICIOUS_COMPILED = [(re.compile(p, re.IGNORECASE), desc) for p, desc in SUSPICIOUS_SEQUENCES]


class LLMSanitizer:
    """
    Post-LLM command sanitization layer.

    Validates and cleans commands generated by the LLM before they
    reach the safety checker and executor. Acts as an additional
    defense-in-depth layer.

    Checks:
    1. Command length limits
    2. Forbidden dangerous patterns (remote exec, disk format, etc.)
    3. Suspicious injection sequences
    4. Structural validity (balanced quotes, no null bytes)
    5. Platform-specific validation
    """

    def sanitize(self, command: str, source: str = "llm") -> SanitizationResult:
        """
        Sanitize a command string.
        Returns SanitizationResult with is_safe=False if command should be blocked.
        """
        warnings: list[str] = []
        # Guard: coerce to str so MagicMock / non-string LLM responses don't crash regex
        if not isinstance(command, str):
            command = str(command)
        original = command
        was_modified = False

        # ── 1. Basic structural checks ──
        if not command or not command.strip():
            return SanitizationResult(
                command="", is_safe=False,
                warnings=["Empty command"], original=original,
            )

        command = command.strip()

        # Remove null bytes
        if "\x00" in command:
            command = command.replace("\x00", "")
            warnings.append("Removed null bytes from command")
            was_modified = True

        # Length check
        if len(command) > MAX_COMMAND_LENGTH:
            return SanitizationResult(
                command=command[:MAX_COMMAND_LENGTH],
                is_safe=False,
                warnings=[f"Command exceeds {MAX_COMMAND_LENGTH} char limit ({len(original)} chars)"],
                was_modified=True, original=original,
            )

        # ── 2. Forbidden pattern check ──
        for pattern, description in _FORBIDDEN_COMPILED:
            if pattern.search(command):
                return SanitizationResult(
                    command=command, is_safe=False,
                    warnings=[f"BLOCKED: {description}"],
                    original=original,
                )

        # ── 3. Suspicious sequence warnings ──
        for pattern, description in _SUSPICIOUS_COMPILED:
            if pattern.search(command):
                warnings.append(f"SUSPICIOUS: {description}")

        # ── 4. Structural validation ──
        structural_issues = self._check_structure(command)
        warnings.extend(structural_issues)

        # ── 5. Platform validation ──
        platform_issues = self._check_platform(command)
        warnings.extend(platform_issues)

        # ── 6. Multi-command injection check ──
        injection_blocked = self._check_injection(command)
        if injection_blocked:
            return SanitizationResult(
                command=command, is_safe=False,
                warnings=[injection_blocked], original=original,
            )

        is_safe = not any(w.startswith("BLOCKED") for w in warnings)

        return SanitizationResult(
            command=command, is_safe=is_safe,
            warnings=warnings, was_modified=was_modified,
            original=original if was_modified else "",
        )

    def _check_structure(self, command: str) -> list[str]:
        """Check structural validity of the command."""
        issues: list[str] = []

        # Unbalanced quotes
        single_quotes = command.count("'") - command.count("\\'")
        double_quotes = command.count('"') - command.count('\\"')
        if single_quotes % 2 != 0:
            issues.append("Warning: unbalanced single quotes")
        if double_quotes % 2 != 0:
            issues.append("Warning: unbalanced double quotes")

        # Unbalanced parentheses/brackets
        for open_c, close_c, name in [("(", ")", "parentheses"), ("{", "}", "braces"), ("[", "]", "brackets")]:
            if command.count(open_c) != command.count(close_c):
                issues.append(f"Warning: unbalanced {name}")

        # Excessive semicolons (possible injection)
        if command.count(";") > 5:
            issues.append("Warning: excessive semicolons — possible command injection")

        return issues

    def _check_platform(self, command: str) -> list[str]:
        """Check platform-specific issues."""
        issues: list[str] = []
        is_windows = platform.system() == "Windows"

        if is_windows:
            # Linux commands on Windows
            linux_only = ["chmod", "chown", "chgrp", "apt-get", "yum", "dnf", "pacman"]
            cmd_start = command.strip().split()[0].lower()
            if cmd_start in linux_only:
                issues.append(f"Warning: '{cmd_start}' is a Linux command — you're on Windows")
        else:
            # Windows commands on Linux/Mac
            win_only = ["cls", "dir", "copy", "del", "type", "tasklist", "taskkill", "ipconfig"]
            cmd_start = command.strip().split()[0].lower()
            if cmd_start in win_only:
                issues.append(f"Warning: '{cmd_start}' is a Windows command — you're on {platform.system()}")

        return issues

    def _check_injection(self, command: str) -> Optional[str]:
        """Detect command injection patterns in LLM output."""
        # Multiple unrelated commands chained suspiciously
        parts = re.split(r'\s*[;&|]{1,2}\s*', command)
        if len(parts) > 8:
            return "BLOCKED: Excessive command chaining (>8 commands) — possible injection"

        # Check for variable expansion attack
        if re.search(r'\$\(.*(?:curl|wget|nc|python).*\)', command):
            return "BLOCKED: Subshell with network command — possible reverse shell"

        # Check for backtick command substitution with dangerous commands
        if re.search(r'`.*(?:curl|wget|nc|python).*`', command):
            return "BLOCKED: Backtick substitution with network command"

        return None
