# Copyright (c) 2024-2026 Abneesh Singh. All rights reserved.
# Proprietary and Confidential - see LICENSE.txt
"""
NeuroShell Shell Script Generator
Converts natural language descriptions into .sh or .ps1 scripts.
Includes error handling, comments, and platform awareness.
"""

import os
import time
from dataclasses import dataclass


@dataclass
class ScriptResult:
    """Generated script result."""
    filename: str
    content: str
    language: str  # "bash" or "powershell"
    description: str = ""
    saved_path: str = ""
    line_count: int = 0

    def display(self) -> str:
        lines = [
            f"\n📜 Generated Script: {self.filename}",
            f"   Language: {self.language} | {self.line_count} lines",
            "",
            self.content,
        ]
        if self.saved_path:
            lines.append(f"\n💾 Saved to: {self.saved_path}")
        return "\n".join(lines)


class ScriptGenerator:
    """Generate shell scripts from natural language."""

    def __init__(self, llm_client=None):
        self.llm = llm_client
        self.is_windows = os.name == "nt"

    def generate(self, description: str, filename: str = None) -> ScriptResult:
        """Generate a script from a natural language description."""
        lang = "powershell" if self.is_windows else "bash"
        ext = ".ps1" if self.is_windows else ".sh"

        if not filename:
            # Generate filename from description
            safe_name = "".join(c if c.isalnum() or c == "_" else "_" for c in description[:30].lower())
            filename = f"{safe_name}{ext}"

        if self.llm:
            return self._generate_with_llm(description, filename, lang)
        else:
            return self._generate_offline(description, filename, lang)

    def _generate_with_llm(self, description: str, filename: str, lang: str) -> ScriptResult:
        """Use LLM to generate a script."""
        system_prompt = (
            f"You are a {lang} script generator. Generate a complete, working {lang} script.\n"
            "Include:\n"
            "- A header comment with description and date\n"
            "- Error handling (set -e for bash, $ErrorActionPreference for PowerShell)\n"
            "- Helpful comments for each section\n"
            "- Input validation where needed\n"
            f"Respond with ONLY the {lang} script code, no markdown fences."
        )

        response = self.llm.generate(
            f"Generate a {lang} script that: {description}",
            system_prompt
        )

        if response.success:
            content = response.text.strip()
            # Remove markdown fences if present
            if content.startswith("```"):
                content = content.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

            return ScriptResult(
                filename=filename,
                content=content,
                language=lang,
                description=description,
                line_count=content.count("\n") + 1,
            )

        return self._generate_offline(description, filename, lang)

    def _generate_offline(self, description: str, filename: str, lang: str) -> ScriptResult:
        """Generate a basic script template without LLM."""
        if lang == "powershell":
            content = self._ps1_template(description)
        else:
            content = self._bash_template(description)

        return ScriptResult(
            filename=filename,
            content=content,
            language=lang,
            description=description,
            line_count=content.count("\n") + 1,
        )

    def save(self, script: ScriptResult, directory: str = None) -> str:
        """Save the generated script to disk."""
        directory = directory or os.getcwd()
        filepath = os.path.join(directory, script.filename)

        with open(filepath, "w", encoding="utf-8", newline="\n") as f:
            f.write(script.content)

        # Make executable on Unix
        if not self.is_windows:
            os.chmod(filepath, 0o755)

        script.saved_path = filepath
        return filepath

    def _bash_template(self, description: str) -> str:
        return (
            f"#!/bin/bash\n"
            f"# {description}\n"
            f"# Generated by NeuroShell on {time.strftime('%Y-%m-%d %H:%M')}\n"
            f"\n"
            f"set -euo pipefail\n"
            f"IFS=$'\\n\\t'\n"
            f"\n"
            f'echo "🚀 Starting: {description}"\n'
            f"\n"
            f"# TODO: Add your commands here\n"
            f"# Example:\n"
            f"# command_1\n"
            f"# command_2\n"
            f"\n"
            f'echo "✅ Done!"\n'
        )

    def _ps1_template(self, description: str) -> str:
        return (
            f"# {description}\n"
            f"# Generated by NeuroShell on {time.strftime('%Y-%m-%d %H:%M')}\n"
            f"\n"
            f'$ErrorActionPreference = "Stop"\n'
            f"\n"
            f'Write-Host "🚀 Starting: {description}" -ForegroundColor Cyan\n'
            f"\n"
            f"# TODO: Add your commands here\n"
            f"# Example:\n"
            f"# command_1\n"
            f"# command_2\n"
            f"\n"
            f'Write-Host "✅ Done!" -ForegroundColor Green\n'
        )
